yupana/processor/kafka_msg_handler.py, yupana/processor/tests_kafka_msg_handler.py
=> Update yupana to use new report structure

openshift/yupana-template.yaml, yupana/api/status/view.py, yupana/config/urls.py
=> Fix status endpoint to follow new path pattern

jenkins/deploy-yupana.sh, openshift/yupana-template.yaml
=> Configuring Autoscale 

docs/host.swagger.yml
=> Converted contents of insights report schema to an example in a blank object

docs/host.swagger.yml
I previously forgot to remove the section so I created a new issues and removed it.
closes #134
=> Removed 'example' section of source_metadata in host.swagger.yml

yupana/processor/abstract_processor.py, yupana/processor/report_processor.py, yupana/processor/report_slice_processor.py, yupana/processor/tests_report_processor.py, yupana/processor/tests_report_slice_processor.py
=> Send request_id, report_id, report_slice_id & host_id via the platform metadata

Jenkinsfile-smoke.groovy
- Added a Jenkinsfile required the e2e smoke test jobs
=> Added Jenkinsfile for e2e smoke tests

yupana/config/settings/base.py, yupana/processor/abstract_processor.py, yupana/processor/tests_report_slice_processor.py
=> Add stale dates to yupana for satellite & discovery

yupana/api/status/model.py
This change will help to mask sensitive information like `CW_AWS_SECRET_ACCESS_KEY` and `DJANGO_SECRET_KEY`.
=> Supress logging of sensitive info

yupana/processor/report_consumer.py, yupana/processor/tests_report_consumer.py
With this PR report_consumer will check the expiry of minio url and will not process the report if the link is expired.
=> Avoid processing older reports

Pipfile, Pipfile.lock, docs/rtd_requirements.txt, scripts/test/consumer.py, yupana-manifest, yupana/processor/report_consumer.py, yupana/processor/report_processor.py, yupana/processor/report_slice_processor.py, yupana/processor/tests_report_consumer.py, yupana/processor/tests_report_slice_processor.py
There are couple of `pyup-scheduled-update-*` branches which suggest to upgrade aiokafka version.
While working on different ticket added few changes around this change so thought to open a pull-request.
+adding @beav into the loop.
=> Upgrade aiokafka version to 0.6.0

Pipfile, Pipfile.lock, docs/rtd_requirements.txt, scripts/test/consumer.py, yupana-manifest, yupana/api/status/tests_view.py, yupana/api/status/view.py, yupana/processor/processor_utils.py, yupana/processor/report_consumer.py, yupana/processor/report_processor.py, yupana/processor/report_slice_processor.py, yupana/processor/tests_report_consumer.py, yupana/processor/tests_report_slice_processor.py
`6594011bb5c993739ce14615c32dfc18c0eac74f`
- [PR 334](https://github.com/quipucords/yupana/pull/334) - Improve Liveness and Readiness checks
- [PR 329](https://github.com/quipucords/yupana/pull/329) - Upgrade aiokafka version to 0.6.0
- [PR 327](https://github.com/quipucords/yupana/pull/327) - Avoid processing older reports
- [PR 331](https://github.com/quipucords/yupana/pull/331) - Transform mtu value to integer
- [PR 328](https://github.com/quipucords/yupana/pull/328) - Remove ip_addrs & mac_addrs fields if empty
=> Release 0.2.6 of Yupana

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
`0104dd097adc85765e7a570c77070dba50a0d06e`
- [PR 333](https://github.com/quipucords/yupana/pull/333) -  add OS major/minor/name to yupana
=>  Release 0.2.7 of Yupana 

yupana/processor/report_processor.py, yupana/processor/tests_report_consumer.py, yupana/processor/tests_report_processor.py
Fixes - [YUPANA-27](https://projects.engineering.redhat.com/browse/YUPANA-27)
=> support reports with bzip2,xz compression including gz

yupana/processor/report_processor.py, yupana/processor/tests_report_consumer.py, yupana/processor/tests_report_processor.py
`47d1fea9359aaecb0d6ae38bdb7c4a1f7f86c352`
- [PR 336](https://github.com/quipucords/yupana/pull/336) - Support reports with bzip2,xz compression including gz
=> Release 0.2.8 of Yupana

Makefile, yupana/processor/report_slice_processor.py, yupana/processor/tests_report_consumer.py
`b2d04d7d7f223f945e77997d6f9d28704cb7d495`
- PR [340](https://github.com/quipucords/yupana/pull/340) - Add owner ID
=> Release 0.2.9 of Yupana

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
`7e21e784c91e568d9774c24b0469fcd9970f3185`
- PR 343 - [transform ipv6, name fields of network-interfaces](https://github.com/quipucords/yupana/pull/343)
=> Release of Yupana 0.2.10

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
`f745786333c469201a36f1f76181c19286dcf2a3`
- PR 346 - [Remove display_name field from host](https://github.com/quipucords/yupana/pull/346)
=> Release of Yupana 0.2.11

yupana/config/settings/base.py, yupana/processor/report_slice_processor.py
`f7bece328ca407b74338d833f7cb984c336e5358`
- [PR 349](https://github.com/quipucords/yupana/pull/349) - Override max request size of Kafka producer
=> Release of Yupana 0.2.12

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
+ adding @ShimShtein into loop for review
=> YUPANA-52 - transform tag's value to string

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
+adding @ShimShtein into loop for review
=> Refs YUPANA-42 - omit invalid bios_uuid

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
+ adding @ShimShtein into loop for review
=> YUPANA-68 - add CentOS enum to fix host OS info

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
[YUPANA 81](https://github.com/quipucords/yupana/commit/b9f6d8d3769f075c659bf1b32bd6178389be46a8)- Update host when kafka msg exceeds max_req_size (#366)
(cherry picked from commit 15e63055bf2bf34de8426128622a8283e9c589cd)
=> Push YUPANA-81 to stable

yupana/processor/report_slice_processor.py, yupana/processor/tests_report_slice_processor.py
- [YUPANA-68](https://github.com/quipucords/yupana/commit/1c854d1aceb2e6cc7be64ca2c10d7d5224c7e85e) - add CentOS enum to fix host OS info
- [YUPANA 81](https://github.com/quipucords/yupana/commit/15e63055bf2bf34de8426128622a8283e9c589cd)- Update host when kafka msg exceeds max_req_size
=> Release of Yupana 0.2.14

yupana/processor/garbage_collection.py
`c62c4ea9f017c6edef2f39101af161eacb6da89a`
- [PR 369](https://github.com/quipucords/yupana/pull/369) - YUPANA-86  - add log statements & try-except in gc processor
=> Release of Yupana 0.2.15

yupana/config/settings/base.py, yupana/processor/garbage_collection.py
i.e reportarchive & reportslicearchive records
=> YUPANA-86 - making use of iterator while deleting outdated records

saas-templates/_imagestreams.yaml, saas-templates/configmap.yaml, saas-templates/yupana-db.yaml, saas-templates/yupana.yaml, yupana/config/settings/base.py, yupana/processor/garbage_collection.py
`f8a178a1d5126f58329b335c69915a07e2f51ca8`
- [PR 375](https://github.com/quipucords/yupana/pull/375) - YUPANA-86 - making use of iterator while deleting outdated records
- [PR 373](https://github.com/quipucords/yupana/pull/373) - Move saas-templates to yupana repo
=> Release of Yupana 0.2.16

clowdapp.yaml
Adding @san7ket into the loop.
=> YUPANA #58 - Add clowdapp for yupana

docs/rtd_requirements.txt
Based on recent [#383](https://github.com/quipucords/yupana/pull/383/files#diff-b9b661d17bb7925e0970d94aec241dd2f44006845f34a23382f7cd0278025b9f) update in yupana-manifest.
=> Fix rtd_requirements

yupana/processor/tests_report_processor.py
Object was initialized before mocking the method.
=> YUPANA-102 fix run_delegate test case
